import time
import sys
import os
import threading
import logging
from logging.handlers import RotatingFileHandler
import requests

# Resolve package name conflicts when executing simulator.py directly
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

# Reconfigure stdout for Windows console UTF-8
reconfigure = getattr(sys.stdout, 'reconfigure', None)
if reconfigure:
    try:
        reconfigure(encoding='utf-8')
    except Exception:
        pass

from simulator.camera import Camera
from simulator.config import BACKEND_URL, LOG_LEVEL, CAMERA_LOCATIONS

def setup_logging():
    """Configure rotating file logging and console logging for simulator."""
    log_dir = os.path.join(parent_dir, 'logs')
    os.makedirs(log_dir, exist_ok=True)
    log_file = os.path.join(log_dir, 'simulator.log')

    log_level_val = getattr(logging, LOG_LEVEL, logging.INFO)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    file_handler = RotatingFileHandler(log_file, maxBytes=10*1024*1024, backupCount=5)
    file_handler.setFormatter(formatter)
    file_handler.setLevel(log_level_val)

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    console_handler.setLevel(log_level_val)

    logger = logging.getLogger("simulator")
    logger.setLevel(log_level_val)
    if not logger.handlers:
        logger.addHandler(file_handler)
        logger.addHandler(console_handler)

    return logger

logger = setup_logging()

def send_telemetry(camera, stop_event):
    """Worker thread function for simulating a single camera and POSTing health data."""
    while not stop_event.is_set():
        try:
            data = camera.tick()

            # Status determination for log output
            if not data["is_online"]:
                status_text = "OFFLINE"
                log_func = logger.warning
            elif data["fault_type"]:
                status_text = f"FAULT: {data['fault_type']}"
                log_func = logger.error
            elif data["cpu_usage"] > 75 or data["memory_usage"] > 75:
                status_text = "WARNING"
                log_func = logger.warning
            else:
                status_text = "ONLINE"
                log_func = logger.info

            log_func(
                f"[{camera.camera_id}] {status_text} | "
                f"CPU: {data['cpu_usage']:5.1f}% | "
                f"MEM: {data['memory_usage']:5.1f}% | "
                f"STO: {data['storage_usage']:5.1f}% | "
                f"LAT: {data['network_latency']:6.1f}ms"
            )

            # Send payload to backend ingestion
            # Try /health, fallback to /api/health
            try:
                response = requests.post(f"{BACKEND_URL}/health", json=data, timeout=5)
            except Exception:
                response = requests.post(f"{BACKEND_URL}/api/health", json=data, timeout=5)

            if response.status_code == 201:
                res = response.json()
                if res.get("new_alerts", 0) > 0:
                    logger.warning(f"[{camera.camera_id}] {res['new_alerts']} new alert(s) generated by API!")

        except requests.ConnectionError:
            logger.warning(f"[{camera.camera_id}] Connection error to API at {BACKEND_URL}. Backend may be restarting...")
        except Exception as e:
            logger.error(f"[{camera.camera_id}] Telemetry error: {e}")

        # Sleep for dynamic interval (check stop_event periodically)
        for _ in range(max(1, int(camera.reporting_interval))):
            if stop_event.is_set():
                break
            time.sleep(1)

def main():
    logger.info("="*60)
    logger.info("CamGuard Enterprise Dynamic Telemetry Simulator")
    logger.info(f"Target API: {BACKEND_URL}")
    logger.info("Status: Spawning camera threads based on settings...")
    logger.info("="*60)

    running_threads = {}  # camera_id -> {"thread": Thread, "stop_event": Event, "camera": Camera}
    stop_orchestrator = False

    def orchestrator():
        nonlocal stop_orchestrator
        while not stop_orchestrator:
            try:
                # Fetch settings from API
                try:
                    res = requests.get(f"{BACKEND_URL}/settings", timeout=3)
                except Exception:
                    res = requests.get(f"{BACKEND_URL}/api/settings", timeout=3)

                if res.status_code == 200:
                    settings = res.json()
                else:
                    settings = {}

                # Extract settings
                camera_count = int(settings.get("camera_count", 10))
                interval = int(settings.get("reporting_interval", 30))
                fault_prob = float(settings.get("fault_probability", 0.05))

                active_ids = {f"CAM-{i:03d}" for i in range(1, camera_count + 1)}

                # Update running threads parameters dynamically
                for cam_id in active_ids:
                    if cam_id in running_threads:
                        cam = running_threads[cam_id]["camera"]
                        cam.reporting_interval = interval
                        cam.fault_probability = fault_prob
                    else:
                        # Spawn new camera thread
                        logger.info(f"[+] Starting camera simulation for {cam_id}")
                        try:
                            cam_num = int(cam_id.split('-')[1])
                            loc = CAMERA_LOCATIONS[(cam_num - 1) % len(CAMERA_LOCATIONS)]
                        except (IndexError, ValueError):
                            loc = "Main Entrance"
                        cam = Camera(
                            camera_id=cam_id,
                            name=f"Camera {cam_id.split('-')[1]}",
                            reporting_interval=interval,
                            fault_probability=fault_prob,
                            location=loc
                        )
                        stop_event = threading.Event()
                        t = threading.Thread(
                            target=send_telemetry,
                            args=(cam, stop_event),
                            daemon=True,
                            name=f"sim-{cam_id}"
                        )
                        running_threads[cam_id] = {
                            "thread": t,
                            "stop_event": stop_event,
                            "camera": cam
                        }
                        t.start()
                        time.sleep(0.2)  # Stagger startups

                # Stop threads for cameras that are no longer in scope
                for cam_id in list(running_threads.keys()):
                    if cam_id not in active_ids:
                        logger.info(f"[-] Stopping camera simulation for {cam_id}")
                        running_threads[cam_id]["stop_event"].set()
                        running_threads[cam_id]["thread"].join(timeout=1.0)
                        del running_threads[cam_id]

            except requests.ConnectionError:
                logger.warning(f"Connection to API ({BACKEND_URL}) failed, retrying sync in 5s...")
            except Exception as e:
                logger.error(f"Orchestrator sync error: {e}")

            # Sleep between checks for rapid config changes responsiveness
            for _ in range(5):
                if stop_orchestrator:
                    break
                time.sleep(1)

    # Start orchestrator thread
    orch_t = threading.Thread(target=orchestrator, daemon=True, name="orch-loop")
    orch_t.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logger.info("Shutting down telemetry threads...")
        stop_orchestrator = True
        orch_t.join(timeout=2)
        for cam_id, data in running_threads.items():
            data["stop_event"].set()
        for cam_id, data in running_threads.items():
            data["thread"].join(timeout=2)
        logger.info("Simulator stopped cleanly.")
        sys.exit(0)

if __name__ == "__main__":
    main()
