"""add index on health_records camera_id

Revision ID: ce5ffc4345be
Revises: 5b78db9d9423
Create Date: 2026-07-13 16:09:18.313010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5ffc4345be'
down_revision = '5b78db9d9423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_records_camera_id'), ['camera_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_records_camera_id'))

    # ### end Alembic commands ###
